version: 1
reporting: checks-v1    # Reports results as "GitHub Checks"
policy:
  pullRequests: public_restricted
tasks:
  - $if: 'tasks_for == "github-pull-request-untrusted"'
    then:
      taskQueueId: docker-compose/generic-worker
      schedulerId: taskcluster-ui
      created: '2022-07-27T13:53:21.190Z'
      deadline: '2022-07-27T16:53:21.190Z'
      payload:
        command:
          - - /bin/bash
            - '-c'
            - for ((i=1;i<=10;i++)); do echo $i; sleep 1; done
        maxRunTime: 30
      metadata:
        name: example-task
        description: An **example** task
        owner: ahal@mozilla.com
        source: http://taskcluster/tasks/create
    else:
      $if: 'tasks_for == "github-pull-request"'
      then:
        taskQueueId: docker-compose/generic-worker
        schedulerId: taskcluster-ui
        created: '2022-07-27T13:53:21.190Z'
        deadline: '2022-07-27T16:53:21.190Z'
        payload:
          command:
            - - /bin/bash
              - '-c'
              - for ((i=1;i<=10;i++)); do echo $i; sleep 1; done
          maxRunTime: 30
        metadata:
          name: example-task
          description: An **example** task
          owner: ahal@mozilla.com
          source: http://taskcluster/tasks/create
