version: 1
reporting: checks-v1    # Reports results as "GitHub Checks"
policy:
  pullRequests: public  # It can be restricted to known collaborators, for instance.
tasks:
  - taskQueueId: built-in/succeed
    schedulerId: taskcluster-ui
    created: '2022-07-27T14:18:02.603Z'
    deadline: '2022-07-27T17:18:02.603Z'
    payload: {}
    metadata:
      name: example-task
      description: An **example** task
      owner: ahal@mozilla.com
      source: http://taskcluster/tasks/create
